### ISSUE TITLE
Passing nil into an option for #initialize causes a NullPointerException.

### ISSUE THREAD

**Issue by stormbrew** [aurorafeint/jruby-memcached#4]
For example:
Memcached.new(['127.0.0.1:11211'], {:prefix_key => nil})

This particularly causes a leakage of a Java exception into ruby code that is rather difficult to debug (it screws up Rails), but that might be a bug in recent versions of jruby. Still, the cext Memcached gem does not mind being given nil for an option hash member.

**Comment by flyerhzm** [comment]
thanks for reporting, it's already fixed, please try jruby-memcached 0.5.1
