### ISSUE TITLE
Make truly compatible as a Rails cache store

### ISSUE THREAD

**Issue by mdespuits** [aurorafeint/jruby-memcached#8]
Currently, `Memcached::Rails` is not a true cache store in the sense of what Rails expects when defining the `config.cache_store` option.

See http://www.intridea.com/blog/2012/3/6/writing-a-custom-rails-cache-store for more info

What would it take to make this possible? It would making a custom wrapper for the app I'm working on a breeze. I'd make a PR, but I don't know the first thing about writing Ruby from Java...

**Comment by mdespuits** [comment]
For example, the following methods should be used for reading, writing, and deleting keys instead of `read`, `write`, and `delete` according to the `ActiveSupport::Cache::Store` implementation.

``` ruby
def read_entry(key, options)
  # some custom behavior...
  super(key, options)
end

def write_entry(key, entry, options)
  # some custom behavior
  super(key, entry, options)
end

def delete_entry(key, options)
  # some custom behavior
  super(key, options)
end
```

**Comment by flyerhzm** [comment]
@mattdbridges you can view my blog post to see how to write jruby gem http://huangzhimin.com/2012/08/23/how-to-write-a-jruby-gem-part-2/, I'd like to merge your pull request

**Comment by mdespuits** [comment]
@flyerhzm Fantastic! I'll get to work on it as soon as I can.

**Comment by dukex** [comment]
Something about it?

**Comment by flyerhzm** [comment]
@dukex I don't have time these days, I'd like to see someone open a pull request for this issue

**Comment by mdespuits** [comment]
@dukex I would love to look into it, but I am a bit too focused on other things. Sorry...
